### ISSUE TITLE
How to use without angular material?

### ISSUE THREAD

**Issue by Hesesses** [gatimus/angular-croppie#1]
I hope this would be possible

**Comment by gatimus** [comment]
Code wise, the directive isn't dependent on material2. Let me test if you can use the library without it.

**Comment by gatimus** [comment]
New version 0.0.5 and updated readme. @Hesesses let me know if this work for you.

**Comment by Hesesses** [comment]
Works perfectly, thank you very much!

This is probably related to croppie, but do you know if it would be possible to set viewport width and height as % instead of pixels? For example width: 100% so it would cover the whole width? I'm trying to archive something like Instagram has

**Comment by gatimus** [comment]
No I don't know. Yes that would related to croppie. I'm not sure how that would work because the resulting copped image dimensions would be based on the size of the browser at the time.
