### ISSUE TITLE
Default imports issue

### ISSUE THREAD

**Issue by Clipperer** [gatimus/angular-croppie#2]
Hello,

First of all - thanks for the great wrapper - it is a pleasure to work with.

I am having issues with the directive import and the    

 "allowSyntheticDefaultImports": true in tsconfig.

Currently the directive does not recognize the type exports, so it needs 
import * as Croppie from 'croppie';
instead of just 
import Croppie from 'croppie';

Of course I believe that with enough effort put in a workaround could be devised, however as I believe others could experience the same issue and the change is not breaking I could propose it as a change in your perfectly done code.

Thank you for the attention and best of regards.

**Comment by gatimus** [comment]
Sorry all for the late response. Version 0.0.6 should resolve all croppie import issues, and follow the [Angular Package Format](https://docs.google.com/document/d/1CZC2rcpxffTDfRDs6p1cfbmKNLA6x5O-NtkJglDaBVs/edit). Please open a new issue if there are any more problems.
