### ISSUE TITLE
@types/croppie has no default export 

### ISSUE THREAD

**Issue by Gytree** [gatimus/angular-croppie#3]
```
ERROR in node_modules/angular-croppie-module/croppie.directive.d.ts(2,8): error
TS1192: Module '"C:/Users/-/angular/node_modules/@types/croppie/index"' has no default export.
```

Hi, i get the above error when i try to compile mi app,  I do not know why it is the error. I new in angular5 and typescript, Could you explain me why it's caused?

**Comment by Timebutt** [comment]
In `croppie.component.ts` do the import as `import * as Croppie from 'croppie';`. The croppie type has been modified since the example in this repow as published. The `CroppieOptions` you'll have to write as `Croppie.CroppieOptions` following said import. Hope this helps!

**Comment by Timebutt** [comment]
Ah no sorry, that doesn't fix the problem at hand, my bad :(

**Comment by Timebutt** [comment]
Ok, found what's going on.
If you use [this](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/0a804aff1a4b75eeac09806ef6188101af406f27/types/croppie/index.d.ts) Typescript definition file, you're good to go with the code as provided in this repository. 

It all has something to do with the way they export the `Croppie` class in the definition file. [This comment](https://github.com/ethereum/web3.js/issues/1248#issuecomment-356094710) explains in more detail what's going on if you're interested.

To solve your problem easily, simply force `npm` to use the typing version that corresponds with the link I provided earlier. Run this and you're set:

`npm install --save @types/croppie@2.5.1`

**Comment by gatimus** [comment]
Sorry all for the late response. Version 0.0.6 should resolve all croppie import issues, and follow the [Angular Package Format](https://docs.google.com/document/d/1CZC2rcpxffTDfRDs6p1cfbmKNLA6x5O-NtkJglDaBVs/edit). Please open a new issue if there are any more problems.
