### ISSUE TITLE
TypeError: __WEBPACK_IMPORTED_MODULE_1_croppie___default.a is not a constructor

### ISSUE THREAD

**Issue by enesyurtlu** [gatimus/angular-croppie#4]
Yesterday i had a problem with `angular-croppie-module`. Cannot activate croppie. Then i searched this and found a solution. 

Solution: Edit `croppie.directive.js`
Change `"import Croppie from 'croppie';"` to `"import { Croppie } from 'croppie';"`

I am using:  
```
@angular: 5.2.7
@angular/cli: 1.7.2
croppie: 2.6.1
angular-croppie-module: 0.0.5
```

**Comment by malqerm** [comment]
Thanks @enesyurtlu, but now I get this message:

> ERROR TypeError: croppie_1.default is not a constructor.

You solution fixed the issue, but it was missing the following line in tsconfig.json:

> "allowSyntheticDefaultImports": true,

Do you have any idea about this issue ?

**Comment by enesyurtlu** [comment]
I have that line in my tsconfig already.

**Comment by ErwinSanquer** [comment]
Hello, I'm new to angular and can't manage to get it work.
I add the 
`"allowSyntheticDefaultImports": true,`

Change `"import Croppie from 'croppie';"` to `"import { Croppie } from 'croppie';"`
But then I have an error in the croppie.directive.d.ts

> Module '".../node_modules/@types/croppie/index"' has no exported member 'Croppie'

I also try to change `"import Croppie from 'croppie';"` to `"import * as Croppie from 'croppie';"`
So the error in the croppie.directive.d.ts vanish.
The project compile well but once I reach the page I still get the error

> __WEBPACK_IMPORTED_MODULE_1_croppie___default.a is not a constructor

I notice that the `npm install --save-dev @types/croppie` installed it for 2.5 version.
Could you send me the `index.d.ts` you have for `@types/croppie`

Any idea ?

I'm using :
```
@angular: 5.2.7
@angular/cli: 1.7.3
croppie: 2.6.1
angular-croppie-module: 0.0.5
```

**Comment by enesyurtlu** [comment]
`// Type definitions for croppie 2.5
// Project: https://github.com/Foliotek/Croppie
// Definitions by: Connor Peet <https://github.com/connor4312>
//                 dklmuc <https://github.com/dklmuc>
//                 Sarun Intaralawan <https://github.com/sarunint>
// Definitions: https://github.com/DefinitelyTyped/DefinitelyTyped

export as namespace Croppie;

export = Croppie;

declare class Croppie {
    constructor(container: HTMLElement, options?: Croppie.CroppieOptions);

    bind(options: {
        url: string,
        points?: number[],
        orientation?: number,
        zoom?: number,
        useCanvas?: boolean,
    }): Promise<void>;

    result(options: Croppie.ResultOptions & { type: 'base64' | 'canvas' }): Promise<string>;
    result(options: Croppie.ResultOptions & { type: 'html' }): Promise<HTMLElement>;
    result(options: Croppie.ResultOptions & { type: 'blob' }): Promise<Blob>;
    result(options: Croppie.ResultOptions & { type: 'rawcanvas' }): Promise<HTMLCanvasElement>;
    result(options?: Croppie.ResultOptions): Promise<HTMLCanvasElement>;

    rotate(degrees: 90 | 180 | 270 | -90 | -180 | -270): void;

    setZoom(zoom: number): void;

    destroy(): void;
}

declare namespace Croppie {
    type CropType = 'square' | 'circle';

    type Format = 'jpeg' | 'png' | 'webp';

    type Type = 'canvas' | 'base64' | 'html' | 'blob' | 'rawcanvas';

    interface ResultOptions {
        type?: Type;
        size?: 'viewport' | 'original' | { width: number, height: number };
        format?: Format;
        quality?: number;
        circle?: boolean;
    }

    interface CroppieOptions {
        boundary?: { width: number, height: number };
        customClass?: string;
        enableExif?: boolean;
        enableOrientation?: boolean;
        enableZoom?: boolean;
        enforceBoundary?: boolean;
        mouseWheelZoom?: boolean;
        showZoomer?: boolean;
        viewport?: { width: number, height: number, type?: CropType };
    }
}
`

**Comment by enesyurtlu** [comment]
@ErwinSanquer change `croppie.directive.js` not `croppie.directive.d.ts`

**Comment by enesyurtlu** [comment]
Cause when you import that library. Angular or Webpack loads compiled .js file. d.ts files doesn't affect.

**Comment by ErwinSanquer** [comment]
When the d.ts file is used then ? Or what for ?

**Comment by andreafalco1991** [comment]
Hi, i would to understand if you think to release a new version of the library with this bugfix?
Thank you for support.

**Comment by andreafalco1991** [comment]
Hi, probably is more simple, for now, use the version 2.5.1  of Croppie library, to solve the problem quickly.
Thanks

**Comment by dkosasih** [comment]
Hi @enesyurtlu, 
When you say
> I have that line in my tsconfig already.
How exactly did you make it work without touching the source code itself?

Thanks

**Comment by enesyurtlu** [comment]
Hi @dkosasih ,
You should have `"allowSyntheticDefaultImports": true,` value in your tsconfig file. Otherwise Typescript doesn't allows to import Croppie library.  I already touched to tsconfig file and croppie.directive.js file.

**Comment by gatimus** [comment]
Sorry all for the late response. Version 0.0.6 should resolve all croppie import issues, and follow the [Angular Package Format](https://docs.google.com/document/d/1CZC2rcpxffTDfRDs6p1cfbmKNLA6x5O-NtkJglDaBVs/edit). Please open a new issue if there are any more problems.
